name: Build and Run Tests
on: [pull_request]
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        java: ["8", "11", "14"]
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Sources
        uses: actions/checkout@v1

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Confirm Java Version
        shell: bash
        run: javac -version

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ubuntu-latest-${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ubuntu-latest-${{ matrix.java }}-gradle

      - name: Build with JDK ${{ matrix.java }}
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: compileJava
      - name: Build with JDK ${{ matrix.java }}
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build

  
